### ISSUE TITLE
I cannot create databases on other hosts, only on my localhost.

### ISSUE THREAD

**Issue by Caletayo** [Tomato6966/remote-sqlite-database#2]
Once when I wanted to create some databases on a more powerful host, I got an error, I tried everything, but it wouldn't let me connect to my databases. I investigated a little about the error, but it was not clear to me what it meant. I was able to use my databases on a local host, but not on another hosting.

**Comment by Tomato6966** [comment]
I dont know what ur error is

The db will work
Only problem u might have is not beeing able to connect

Aka u must prolly open ur port from ur firewall
And make sure that password and username is correct

**Comment by Caletayo** [comment]
Thank you tomato
