### ISSUE TITLE
This database does not work with milrato

### ISSUE THREAD

**Issue by Caletayo** [Tomato6966/remote-sqlite-database#4]
I tried to run the database for milrato shardeado and it does not work for me.

I tried by all means to create one by one the tables that were talked about in a previous problem and they do not work. They do not save the data

I put bot prefix prefix x!

x!help does not work

And it works with the prefix from before and the setups the same. I set up something like tickets and it tells me the bot. ❌ I have not found your configuration in the database.

Any solution?

**Comment by anishdevtech** [comment]
Milrato open source use enmap not this if you have customised it then check are your pass port and other stuff is correct
